# Generated by Django 2.2.10 on 2020-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0006_delete_simulateddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindSpeedSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('current_wind_speed', models.FloatField(default=0)),
            ],
        ),
    ]
